### ISSUE TITLE
Printing of Decs

### ISSUE THREAD

**Issue by andreasnoack** [stevengj/DecFP.jl#13]
The following example has received some attention lately
```jl
julia> d"1.05"*d"0.7"
+735E-3
```
I wondered if it would be possible to print this similarly to how the binary floats are printed, i.e. such the result is `+7.35E-1`?

**Comment by stevengj** [comment]
One would have to dig through the underlying C library to see if there is an option to change the printing.  I agree that the default format is annoying.  (Maybe the decNumber library is better in this regard.)

**Comment by andreasnoack** [comment]
I've just had a look at the source and I don't think this can be changed although there are not many comments to help you with the reading. I also had a look at the [paper](http://www.lirmm.fr/arith18/papers/CorneaM_Decimal_ARITH18.pdf) behind the library and it is using the same notation so I guess there is nothing to do unless we want to modify the source (which I don't).

**Comment by ScottPJones** [comment]
@stevengj The decNumber package does allow you do convert to string from any of the formats, and let's you choose scientific or engineering notation (which seems to be what you are getting).
For example, decNumberToEngString and decNumberToString.
