### ISSUE TITLE
Into standard JuliaLang library

### ISSUE THREAD

**Issue by hyiltiz** [stevengj/DecFP.jl#16]
Do you think it should every make into the standard library so that we can use it WITHOUT `Using` this library? Maybe merging it into the `Base` would be great.

**Comment by stevengj** [comment]
Probably not.  Why is it a problem to have this in an external package?  In Julia there is no particular performance or functionality advantage to code in the Base module.

**Comment by ScottPJones** [comment]
The one thing that I think might be good to have in Base would simply be the definitions of the different bitstype IEEE decimal formats (bid & dpd, 16/32/64/128), and the abstract decimal floating point type.
What do you think, Steven?

**Comment by stevengj** [comment]
Closing in favor of JuliaLang/julia#14241
