### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by EricForgy** [stevengj/DecFP.jl#22]
Hi,

The last tagged version of DecFP comes with a ton of deprecation warnings. I didn't see any outstanding PRs so fixed them myself. While preparing a PR, I realized that the deprecation warnings are fixed on master.

Is there anything holding up tagging a new version so that newbies (like me) do not get scared away from ODBC.jl by seeing the deprecation warnings?

Thanks

**Comment by quinnj** [comment]
@stevengj, I went ahead and opened a new PR to METADATA.jl to tag a new version if you'll tag the release in the repo here.

**Comment by quinnj** [comment]
METADATA PR reference: https://github.com/JuliaLang/METADATA.jl/pull/5440

**Comment by tkelman** [comment]
ping @stevengj would you be okay with giving @quinnj (and maybe other maintainers of packages that depend on this one?) commit access here?

**Comment by stevengj** [comment]
Just invited @quinnj to commit access.

**Comment by ranjanan** [comment]
Would it be possible to tag yet another version please? v0.1.2 has lingering deprecation warnings, but master doesn't.

**Comment by ranjanan** [comment]
@quinnj @stevengj Could you guys tag one more release version please? The latest tagged version  on METADATA is 2 months old now and does not include that depwarn fixes that #24 did.

**Comment by stevengj** [comment]
Tagged.
