### ISSUE TITLE
floating point exceptions on Windows

### ISSUE THREAD

**Issue by simonbyrne** [stevengj/DecFP.jl#28]
The package appears to be enabling trapping of floating point exceptions, and not setting them back, see https://github.com/JuliaLang/julia/issues/18065#issuecomment-240473511

**Comment by andreasnoack** [comment]
More specifically, the change happens when calling `_sub` here https://github.com/stevengj/DecFP.jl/blob/master/src/DecFP.jl#L206. You can check the value with
```jl
ccall(:_controlfp, Cuint, (Cuint,Cuint), 0,0)
```

**Comment by stevengj** [comment]
Only on Windows?

**Comment by stevengj** [comment]
(I didn't even realize that we had working Windows binaries yet?  I had some trouble cross-compiling.)

**Comment by andreasnoack** [comment]
> Only on Windows?

Yes. It appears so. No problems on Linux and OS X.

**Comment by stevengj** [comment]
I've been poring over the Intel source code, and I'm not seeing anything that sets floating-point traps.  (The library has its own internal floating-point exception flags.)  Could this be some gcc option messing things up?

**Comment by stevengj** [comment]
Aha, I think I found it.  `bid_conf.h` has:
```c
if !defined(BID_MS_FLAGS) && (defined(_MSC_VER) && !defined(__INTEL_COMPILER))
#   define BID_MS_FLAGS
#endif

#if (defined(_MSC_VER) && !defined(__INTEL_COMPILER))
#   include <math.h>    // needed for MS build of some BID32 transcendentals (h\
ypot)                                                                           
#endif



#if defined (UNCHANGED_BINARY_STATUS_FLAGS) && defined (BID_FUNCTION_SETS_BINARY_FLAGS)
#   if defined( BID_MS_FLAGS )

#       include <float.h>

        extern unsigned int __bid_ms_restore_flags(unsigned int*);

#       define BID_OPT_FLAG_DECLARE() \
            unsigned int binaryflags = 0;
#       define BID_OPT_SAVE_BINARY_FLAGS() \
             binaryflags = _statusfp();
#        define BID_OPT_RESTORE_BINARY_FLAGS() \
              __bid_ms_restore_flags(&binaryflags);

#   else
#       include <fenv.h>
#       define BID_FE_ALL_FLAGS FE_INVALID|FE_DIVBYZERO|FE_OVERFLOW|FE_UNDERFLOW|FE_INEXACT
#       define BID_OPT_FLAG_DECLARE() \
            fexcept_t binaryflags = 0;
#       define BID_OPT_SAVE_BINARY_FLAGS() \
            (void) fegetexceptflag (&binaryflags, BID_FE_ALL_FLAGS);
#       define BID_OPT_RESTORE_BINARY_FLAGS() \
            (void) fesetexceptflag (&binaryflags, BID_FE_ALL_FLAGS);
#   endif
#else
#   define BID_OPT_FLAG_DECLARE()
#   define BID_OPT_SAVE_BINARY_FLAGS()
#   define BID_OPT_RESTORE_BINARY_FLAGS()
```
Notice that it specifically checks for `_MSC_VER` to enable Windows-specific code, which won't work with MinGW.

Some playing around with these preprocessor options should hopefully fix it.

**Comment by stevengj** [comment]
In particular, if I just add `-DBID_MS_FLAGS` to the mingw cpp flags, maybe it will work.

**Comment by stevengj** [comment]
I just uploaded new 32- and 64-bit Windows DLLs, and AppVeyor is green!

Is the issue with fp exceptions on Windows fixed?

**Comment by stevengj** [comment]
Yup, the exception problem seems to be gone.
