### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by quinnj** [stevengj/DecFP.jl#35]
It looks like there is an `isapprox` [failure on 0.4](https://travis-ci.org/stevengj/DecFP.jl/jobs/216106177), and a concerning segfault that happened on the [linux nightly travis build](https://travis-ci.org/stevengj/DecFP.jl/jobs/216106179), but not osx.

**Comment by stevengj** [comment]
Maybe the default `isapprox` tolerance was too low in 0.4?

**Comment by stevengj** [comment]
At this point, it might be easier to just drop 0.4 support anyway.

**Comment by stevengj** [comment]
Closed by v0.2.0 tag.  We should tag v0.3 next since the type changed, although it should be API-compatible.
