### ISSUE TITLE
String parsing doesn't work for Dec128 type

### ISSUE THREAD

**Issue by ScottPJones** [stevengj/DecFP.jl#54]
On v0.6.2, I ran into the following problem:
```julia
julia> parse(Dec128, "56123")
56123.0

julia> parse(Dec128, "561234")
0.0
```

I'll try to figure it out and submit a PR later, unless you already have a fix in the works for this.

**Comment by stevengj** [comment]
This might be a bug in the underlying Intel library, since `parse` is just calling `__bid128_from_string`.
```jl
julia> parse(Dec128, "561234e0")
0.0

julia> parse(Dec128, "561234e1")
5.61234e+06
```

**Comment by stevengj** [comment]
(They told me two weeks ago that there would be a new release "within days" (#47).)

**Comment by stevengj** [comment]
No, it looks like it's getting parsed correctly, but there is an output bug:
```
julia> Dec64(parse(Dec128, "561234"))
561234.0
```

**Comment by stevengj** [comment]
Oh, this is a duplicate of #47.   The problem is that the printing function calls `exp10` before rounding, and hence it hits #47.  See there for a patch, which we are waiting for Intel to release.

**Comment by quinnj** [comment]
We should move this repo to use the new BinaryBuilder.jl and BinaryProvider.jl repos instead of BinDeps.jl. That would allow us to apply the fix ourselves in the mean time.

**Comment by stevengj** [comment]
We can apply the fix ourselves with BinDeps too.
