### ISSUE TITLE
0.3 compatibility

### ISSUE THREAD

**Issue by stevengj** [stevengj/DecFP.jl#8]
Currently, it only works with 0.4, which is not really acceptable.

**Comment by stevengj** [comment]
Got it at least loading with 0.3, but have some kind of weird corruption that I can't figure out in 0.3:
```jl
julia> using DecFP
julia> d"1.0"
+140734667966048E-398
julia> reinterpret(Uint64, d"1.0")
0x0000000000000000
```
Something has apparently changed with how `bitstype` is handled? (cc: @vtjnash)

I'm not sure it's actually worth it.  I can just make this package require Julia 0.4.

**Comment by vtjnash** [comment]
it's quite possible the ccall fixes changed the calling convention for Dec128, depending on what the system you are on

**Comment by stevengj** [comment]
But why would this affect `Dec64`?

**Comment by vtjnash** [comment]
nvm, it shouldn't i just skimmed the code too quickly.

unrelated note: `cglobal` (like `ccall`) is a compile-time intrinsic, so it is zero-cost to copy it to each usage site (perhaps in macro form `@flags` to reduce typing?) instead of putting it in `__init__`

**Comment by PallHaraldsson** [comment]
Just close, since "it only works with 0.4, which is not really acceptable" is just no longer true..
